export const sortHelper = {
  shorten: {
    url: ['url'],
    alias: ['alias'],
    createdBy: ['createdBy', 'fullname'],
  },
  open_campus: {
    nama: ['nama'],
    asal_sekolah: ['asal_sekolah'],
    no_hp: ['no_hp'],
    email: ['email'],
    fakultas1: ['fakultas1', 'nama'],
    fakultas2: ['fakultas2', 'nama'],
    departemen1: ['departemen1', 'nama'],
    departemen2: ['departemen2', 'nama'],
    statusPendaftaran: ['statusPendaftaran', 'id'],
    createdAt: ['createdAt'],
  },
  forda_member: {
    nama: ['nama'],
    nik: ['nik'],
    asal_sekolah: ['asal_sekolah'],
    alamat_sekolah: ['alamat_sekolah'],
    no_hp: ['no_hp'],
    email: ['email'],
    kelompok_ujian: ['kelompok_ujian'],
    kelompokUjian: ['kelompokUjian', 'nama_penjurusan'],
  },
  forda_order: {
    jumlah_tiket: ['jumlah_tiket'],
    harga: ['harga'],
    opsi_pembayaran: ['opsi_pembayaran'],
    createdAt: ['createdAt'],
    kode_voucher: ['kode_voucher'],
    statusPendaftaran: ['statusPendaftaran'],
  },
};
